# src/upload_youtube.py
import os
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from oauth2client.client import OAuth2Credentials

def upload_video(video_path, title):
    client_id = os.getenv("YOUTUBE_CLIENT_ID")
    client_secret = os.getenv("YOUTUBE_CLIENT_SECRET")
    refresh_token = os.getenv("YOUTUBE_REFRESH_TOKEN")

    credentials = OAuth2Credentials(
        access_token=None,
        client_id=client_id,
        client_secret=client_secret,
        refresh_token=refresh_token,
        token_expiry=None,
        token_uri="https://oauth2.googleapis.com/token",
        user_agent=None,
        revoke_uri="https://oauth2.googleapis.com/revoke"
    )

    credentials.refresh(None)

    youtube = build("youtube", "v3", credentials=credentials)

    request_body = {
        "snippet": {
            "title": title[:100],
            "description": "🎥 فيديو تم إنشاؤه تلقائيًا باستخدام الذكاء الاصطناعي",
            "tags": ["AI", "autogenerated", "shorts"],
            "categoryId": "22"
        },
        "status": {
            "privacyStatus": "public",  # أو "unlisted" أو "private"
            "madeForKids": False
        }
    }

    media = MediaFileUpload(video_path, chunksize=-1, resumable=True, mimetype="video/mp4")

    try:
        request = youtube.videos().insert(part="snippet,status", body=request_body, media_body=media)
        response = request.execute()
        print("✅ Video uploaded successfully:", response["id"])
    except Exception as e:
        print("❌ Upload failed:", e)
